# Generated by Django 2.2.12 on 2022-08-09 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatchapp', '0002_auto_20220809_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='whatchapp.StreamPlatform'),
            preserve_default=False,
        ),
    ]
